---

- hosts: localhost
  tasks:
    
# install basic packages

  - name: Install homebrew packages 
    homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - htop
      - zsh
      - python3
      - nvim
      - ripgrep
      - ccls
      - wget
      - npm
      - tmux
      - tree
    

# tmux plugins
  - name: setup tmux plugin manager
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

# pip installer

  - name: install pip packages
    become: true
    pip:
      name: pexpect, matplotlib, numpy, scipy, pyright

# install oh-my-zsh

  - name: install oh-my-zsh
    shell: wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    args:
      creates: ./install.sh

# install p10k

  - name: install p10k
    ansible.builtin.command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ ansible_env.HOME }}/powerlevel10k
    args:
      creates: "{{ ansible_env.HOME }}/powerlevel10k"

  - name: search .zshrc for p10k theme
    shell: grep /pwerlevel10k/powerlevel10k.zsh-theme {{ ansible_env.HOME }}/powerlevel10k/powerlevel10k.zsh-theme 
    register: p10k_grep_results
    ignore_errors: true
    failed_when: 0

  - name: populate ~/.zshrc with p10k
    shell: echo "source {{ ansible_env.HOME }}/powerlevel10k/powerlevel10k.zsh-theme" >> {{ ansible_env.HOME }}/.zshrc

# install dot files

  - name: install nvim dot files
    ansible.builtin.command: cp ./nvim/init.vim {{ ansible_env.HOME }}/.config/nvim/

  - name: install nvim dot files
    ansible.builtin.command: cp -r ./nvim/after/ {{ ansible_env.HOME }}/.config/nvim/

  - name: install nvim dot files
    ansible.builtin.command: cp -r ./nvim/autoload/ {{ ansible_env.HOME }}/.config/nvim/

  - name: install tmux dot file
    ansible.builtin.command: cp ./.tmux.conf {{ ansible_env.HOME }}/
